project:
  type: website
  output-dir: docs

website:
  title: "Aras Edes's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ar-Ed
      - icon: linkedin
        href: https://www.linkedin.com/in/aras-ede%C5%9F/
format:
  html:
    theme: cosmo
    css: styles.css



